import { canReach as arvancloud } from "detect-conditions/_internal/can-reach/arvancloud";
import { canReach as azion } from "detect-conditions/_internal/can-reach/azion";
import { canReach as browser } from "detect-conditions/_internal/can-reach/browser";
import { canReach as bun } from "detect-conditions/_internal/can-reach/bun";
import { canReach as default_ } from "detect-conditions/_internal/can-reach/default";
import { canReach as deno } from "detect-conditions/_internal/can-reach/deno";
import { canReach as development } from "detect-conditions/_internal/can-reach/development";
import { canReach as edgeLight } from "detect-conditions/_internal/can-reach/edge-light";
import { canReach as edgeRoutine } from "detect-conditions/_internal/can-reach/edge-routine";
import { canReach as electron } from "detect-conditions/_internal/can-reach/electron";
import { canReach as fastly } from "detect-conditions/_internal/can-reach/fastly";
import { canReach as import_ } from "detect-conditions/_internal/can-reach/import";
import { canReach as kiesel } from "detect-conditions/_internal/can-reach/kiesel";
import { canReach as lagon } from "detect-conditions/_internal/can-reach/lagon";
import { canReach as moddable } from "detect-conditions/_internal/can-reach/moddable";
import { canReach as module } from "detect-conditions/_internal/can-reach/module";
import { canReach as moduleSync } from "detect-conditions/_internal/can-reach/module-sync";
import { canReach as netlify } from "detect-conditions/_internal/can-reach/netlify";
import { canReach as node } from "detect-conditions/_internal/can-reach/node";
import { canReach as nodeAddons } from "detect-conditions/_internal/can-reach/node-addons";
import { canReach as production } from "detect-conditions/_internal/can-reach/production";
import { canReach as reactNative } from "detect-conditions/_internal/can-reach/react-native";
import { canReach as reactServer } from "detect-conditions/_internal/can-reach/react-server";
import { canReach as require_ } from "detect-conditions/_internal/can-reach/require";
import { canReach as wasmer } from "detect-conditions/_internal/can-reach/wasmer";
import { canReach as worker } from "detect-conditions/_internal/can-reach/worker";
import { canReach as workerd } from "detect-conditions/_internal/can-reach/workerd";
import { canReach as worklet } from "detect-conditions/_internal/can-reach/worklet";

export const isModuleSync = moduleSync;
export const isNodeAddons = nodeAddons;
export const isImport = import_;
export const isRequire = require_;
export const isDevelopment = development;
export const isProduction = production;
export const isModule = module;
export const isBrowser = browser;
export const isKiesel = kiesel;
export const isWasmer = wasmer;
export const isModdable = moddable;
export const isLagon = lagon;
export const isArvancloud = arvancloud;
export const isAzion = azion;
export const isFastly = fastly;
export const isEdgeRoutine = edgeRoutine;
export const isEdgeLight = edgeLight;
export const isReactServer = reactServer;
export const isNetlify = netlify;
export const isWorkerd = workerd;
export const isReactNative = reactNative;
export const isElectron = electron;
export const isBun = bun;
export const isDeno = deno;
export const isWorklet = worklet;
export const isWorker = worker;
export const isNode = node;
export const isDefault = default_;
